let images = [
    "images/Tilda_Icons_42_restaurant_breakfast.svg",
    "images/Tilda_Icons_42_restaurant_burger.svg",
    "images/Tilda_Icons_42_restaurant_candle.svg",
    "images/Tilda_Icons_42_restaurant_card.svg",
    "images/Tilda_Icons_42_restaurant_chicken.svg",
    "images/Tilda_Icons_42_restaurant_chillout.svg",
    "images/Tilda_Icons_42_restaurant_coctail.svg",
    "images/Tilda_Icons_42_restaurant_cook.svg",
    "images/Tilda_Icons_42_restaurant_dessert.svg",
    "images/Tilda_Icons_42_restaurant_dietary.svg",
    "images/Tilda_Icons_42_restaurant_dish.svg",
    "images/Tilda_Icons_42_restaurant_fooddelivery.svg",
    "images/Tilda_Icons_42_restaurant_fruits.svg",
    "images/Tilda_Icons_42_restaurant_furniture.svg",
    "images/Tilda_Icons_42_restaurant_khinkali.svg",
    "images/Tilda_Icons_42_restaurant_location.svg",
    "images/Tilda_Icons_42_restaurant_menu.svg",
    "images/Tilda_Icons_42_restaurant_online.svg",
    "images/Tilda_Icons_42_restaurant_pasta.svg",
    "images/Tilda_Icons_42_restaurant_phone.svg",
    "images/Tilda_Icons_42_restaurant_pizza.svg",
    "images/Tilda_Icons_42_restaurant_seafood.svg",
    "images/Tilda_Icons_42_restaurant_soup.svg",
    "images/Tilda_Icons_42_restaurant_spicy.svg",
    "images/Tilda_Icons_42_restaurant_sushi.svg",
    "images/Tilda_Icons_42_restaurant_taco.svg",
    "images/Tilda_Icons_42_restaurant_teapot.svg",
    "images/Tilda_Icons_42_restaurant_vegan.svg",
    "images/Tilda_Icons_42_restaurant_waiter.svg",
    "images/Tilda_Icons_42_restaurant_wi-fi.svg"
]

images.sort(() => Math.random() - 0.5);